### ISSUE TITLE
Book a table

### ISSUE THREAD

**Issue by Martiless** [Martiless/nondairy-godmother#1]
### User Story:
As a **Customer** I want to **book a table** at the restaurant for a **particular date and time**

***

### Acceptance Criteria:
- Customer is able to book a table
- Customer can select the date and time they wish 
- Customer can pick the number of people that will be eating 

***

### Tasks: 
- [x] Create HTML & CSS for bookings page
- [x] Use Django models to make all aspects of the booking form a requirement
- [x] Create pop-out message to confirm booking
