### ISSUE TITLE
Manage Bookings

### ISSUE THREAD

**Issue by Martiless** [Martiless/nondairy-godmother#10]
### User Story:

- As an **Owner** I can **manage all bookings** so that **the restaurant doesn't get over booked**

***

### Acceptance Criteria:
- As an Owner I can assess the admin set so I can view all the bookings for the restaurant 
- As an Owner I can assess the admin set so I can cancel a booking, which will then be updated in the users "My Bookings" page

***

### Tasks:

- [x] Set up the bookings model for use in site admin area
- [x] Test to ensure site admin area works correctly
- [x] Test to ensure when a bookings is removed from the backend it is reflected in the users "My Bookings" page
