### ISSUE TITLE
View Menu

### ISSUE THREAD

**Issue by Martiless** [Martiless/nondairy-godmother#2]
### User Story:
As a **Customer** I can **view the menu** so that **decide if I like the options in this restaurant**

***

### Acceptance Criteria:
- Customer can view all three menus for the restaurant 
- Customer can download a copy of the menu from the website

***

### Tasks: 
- [x] Create HTML page to display link for all three menus
- [x] Make menus open on a new page
- [x] Upload PDF versions of all three menus
- [x] Make PDF menus downloadable
