### ISSUE TITLE
Sign up for Newsletter

### ISSUE THREAD

**Issue by Martiless** [Martiless/nondairy-godmother#3]
As a **Customer** I can **sign up for a newsletter** so that **I can be kept up to date on the restaurant news**

## Acceptance Criteria:
- Customer is able to sign up for the monthly newsletter
-  Customers information is added to a database for the owners 

## Tasks: 
- [x] Use HTML & CSS to add sign up form to a Newsletter page 
- [x] Create message to confirm sign up is complete
- [x] Make all aspects of the sign up form a requirement
- [x] Link sign up form with database
