### ISSUE TITLE
Join the restaurant club

### ISSUE THREAD

**Issue by Martiless** [Martiless/nondairy-godmother#4]
### User Story:
As a **Customer** I can **join the exclusive club** so that **I can receive discounts and offers**

***

### Acceptance Criteria:
- Customer can sign up for club 
- Customer information is gathered on a database separate to the newsletter database
- Customer receives "Welcome to the Club" email 
- Customer gets a 10% off welcome discount code
- Customer can log in on the website to see available offers

***
 
### Tasks: 
- [ ] Use HTML & CSS to create join the club page
- [ ] Create Join the club form 
- [ ] Link the form to a database
- [ ] Create monthly offer that will appear on bookings page once the customer has logged in
